### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by KhimarikMayer** [SyndiShanX/Update-Classes#1]
Add txt files for old svg and new svg links for images, they on discord can be changed on discord themes, just on browser need join for ctrl+shift+i and click on the right mouse button to very first top svg xmlns, join to copy, then copy element

Example old and new links:
old - https://discord.com/assets/1i53g04r2131340a4btggt.svg;
new - https://discord.com/assets/caa42aa2e3b055313b4c.svg.
Especially add it, on https://syndishanx.github.io/Website/ to tab "More..."

**Comment by SyndiShanX** [comment]
I'd need a database of the changes from one link to another which doesn't seem like it would be possible
